# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: show this help
    cmds:
      - task --list-all
    silent: true

  install:
    cmds:
      - go install github.com/go-perf/go-perftuner@latest

  run-*:
    vars:
      NAME: '{{index .MATCH 0}}'
    cmds:
      - go test -c -o {{.NAME}}-bench.exec ./{{.NAME}}
      - time ./{{.NAME}}-bench.exec -test.v -test.benchmem -test.bench ^Benchmark -test.count 3 -test.run ^$ > bench-raw.txt
      - go-perftuner bstat bench-raw.txt | tee bench.txt
