# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: show this help
    cmds:
      - task --list-all
    silent: true

  install:
    cmds:
      - go install github.com/go-perf/go-perftuner@latest

  run-*:
    vars:
      NAME: '{{index .MATCH 0}}'
      FLAGS: '-test.v -test.benchmem -test.run ^$ -test.count 10'
    dir: '{{.NAME}}'
    cmds:
      - go test -c -o bench.exec
      - time ./bench.exec {{.FLAGS}} -test.bench ^Benchmark > bench-raw.txt
      - rm bench.exec
      - go-perftuner bstat bench-raw.txt | tee bench.txt
